import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { BigInfoCard } from "../components";
import styles from "../styles/home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BigInfoCard 
          media={{src:"/infocard.png", alt:"biginfocard"}} 
          title="Ramadhan berbagi 1443H Masjid Al-Ikhlas Bulusan"
          date="18 Mei 2022"
          content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id imperdiet morbi sed sit sed sed tincidunt eu. Facilisis at dolor, tincidunt consectetur massa sed augue sit pharetra. Semper odio viverra suscipit fringilla est scelerisque. Aliquam nisi, nulla libero, sapien, leo semper arcu, libero. Sed dictumst purus ut arcu fermentum, a arcu est tempor. Tellus scelerisque fermentum neque, dictum id diam consequat. Cursus vitae, odio urna purus. Dignissim consectetur imperdiet elit mi ut."
          href="instagram.com"></BigInfoCard>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
